In [1]:
import pandas as pd
import itertools
from datetime import datetime



df = pd.read_csv('data_dzebi_casa.csv',index_col=[0])

In [2]:
df.columns

Index(['date', 'arrondissement', 'offer link', 'title', 'price',
       'localization', 'description', 'more', 'caracteristiques', 'X', 'Y',
       'type_link', 'type_title', 'surface', 'pieces', 'chambre', 'bains',
       'age', 'etage', 'Réfrigérateur', 'Salon européen', 'TV', 'Vue sur mer',
       'Piscine', 'Concierge', 'Cuisine équipée', 'Internet', 'Cheminée',
       'Sécurité', 'Chambre rangement', 'Parquet', 'Ascenseur',
       'Chauffage central', 'Salon Marocain', 'Machine à laver', 'Garage',
       'Marbre', 'Porte blindée', 'Vue sur les montagnes', 'Climatisation',
       'Jardin', 'Antenne parabolique', 'Double vitrage', 'Terrasse',
       'Carrelage', 'Micro-ondes', 'Four', 'prix/m²'],
      dtype='object')

In [8]:
def string_to_date(string):
    
    if len(string)==10:
        return datetime.strptime(string, "%d/%m/%Y")
    
    else :
        string = string[:10]
        return datetime.strptime(string, "%Y-%m-%d")
    


def keep_only_digits(string):
    if string is not None:
        
        if '²' in string:
            
        
            string = string.replace("²", "")
    
        return(''.join(filter(str.isdigit,string)))
    
    else:
        return None



def price_string_to_float(string):
    
    if isinstance(string, str):
        
        string = string.lower()
        
        if 'dh' in string:
        
            return(float(keep_only_digits(string)))
        
        elif 'eur' in string:
            
            return(float(keep_only_digits(string))*10.5)
        
        else:
            
            return(float(keep_only_digits(string))*9)
        



def get_X_Y(string, axe='X'):
    
    if string:
    
        dic_pos = eval(string)

        if axe=='X':

            return dic_pos['x']
        else:
            return dic_pos['y']
        
def get_type_from_link(link):
    
    link = link.lower()
    
    #combinaison_app = ['app','apartement','apart','apt','aprt']
    
    
        
    
    if ('app'  in link) or ('apartement' in link) or ('apart' in link) or ('apt' in link) or ('aprt' in link): #bricoul a modifi
        return 'A'
    elif 'maison' in link:
        return 'M'
    elif 'villa' in link:
        return 'V'
    elif 'riad' in link:
        return 'R'
    
    elif 'immeuble' in link:
        return 'I'
    
    elif 'studio' in link:
        return 'S'
    elif 'duplex' in link:
        return 'D'
    else:
        return 'Jesspa'

In [9]:
def eval_2(string):

    if isinstance(string,str):
        return eval(string)
    else:
        return None

def index_by_word(string,L):
    
    LL = [string in w for w in L]
    
    if sum(LL)==1:
        return(LL.index(True))
    
    elif sum(LL)==0:
        return None
    
    else:
        raise Exception(f"7adari! {string} kayn fkter mn blassa")
        
        

keywords = ['m²','Pièce','Chambre','bain','an','étage']

Etat = ['Bon état','À rénover','Nouveau']

cols = ['surface','pieces','chambre','bains','age','etage']

def flatten_more(df):
    #parse the column more
    L_more = []

    for row in df.more:
        L_more.append(eval(row))

    # create new list to store values
    surface = []
    pieces = []
    chambre = []
    bains = []
    age = []
    etage = []
    L_index = []

    # c conpliki    
    for elem in L_more:

        index = [index_by_word(key,elem) for key in keywords]
        L_index.append(index)

        #print(index)


    for i,row in enumerate(L_index):

        if row[0] is not None:
            surface.append(L_more[i][row[0]])
        else:
            surface.append(None)



        if row[1] is not None:    
            pieces.append(L_more[i][row[1]])
        else:
            pieces.append(None)




        if row[2] is not None:
            chambre.append(L_more[i][row[2]])
        else:
            chambre.append(None)




        if row[3] is not None:
            bains.append(L_more[i][row[3]])
        else:
            bains.append(None)



        if row[4] is not None:
            age.append(L_more[i][row[4]])
        else:
            age.append(index[4])


        if row[5] is not None:
            etage.append(L_more[i][row[5]])
        else:
            etage.append(None)
            
            
    for col in cols:

        df[col] = eval(col)


    return df

In [10]:
def eval_2(string):

    if isinstance(string,str):
        return eval(string)
    else:
        return None



def columns_to_numbers(df):
    
    
    df['surface']=df['surface'].apply( lambda x : eval_2(keep_only_digits(x) )) #7adari bug hna si surface none
    
    df['pieces']=df['pieces'].apply( lambda x : eval_2(keep_only_digits(x) ))
    
    df['chambre']=df['chambre'].apply( lambda x : eval_2(keep_only_digits(x) ))
    
    
    df['bains']=df['bains'].apply( lambda x : eval_2(keep_only_digits(x) ))
    
    df['etage'] = df['etage'].apply( lambda x : eval_2(keep_only_digits(x) ))
    
    return df



def flatten_carac(df):
    L_carac = []

    for e in df.caracteristiques:
        L_carac.append(eval(e))

    merged = list(itertools.chain(*L_carac))

    unique = list(set(merged))

    unique.remove('')
    
    for var in unique:
        
        L=[]
        
        for row in L_carac:
            if var in row:
                L.append(1)
            else:
                L.append(None)
                
                
        df[var] = L
        
        
    return df

In [11]:
df['price'] = df['price'].apply( lambda x : price_string_to_float(x))

df['X'] = df['localization'].apply(lambda loc : get_X_Y(loc, axe='X'))

df['Y'] = df['localization'].apply(lambda loc : get_X_Y(loc, axe='Y'))

df['type_link'] = df['offer link'].apply(lambda link : get_type_from_link(link))

df['type_title'] = df['title'].apply(lambda link : get_type_from_link(link))

df['date'] = df['date'].apply(lambda x : string_to_date(x))   

df = flatten_more(df)

df = columns_to_numbers(df)
df = flatten_carac(df)

df['prix/m²'] = round(df['price']/df['surface'],2)

In [12]:
# bricoul

def istislam(x):
    if isinstance(x,str):
        return x
    else:
        return None
    
df['age'] = df['age'].apply(lambda x : istislam(x))

In [20]:
print(len(df))
print(df.columns)

8328
Index(['date', 'arrondissement', 'offer link', 'title', 'price',
       'localization', 'description', 'more', 'caracteristiques', 'X', 'Y',
       'type_link', 'type_title', 'surface', 'pieces', 'chambre', 'bains',
       'age', 'etage', 'Réfrigérateur', 'Salon européen', 'TV', 'Vue sur mer',
       'Piscine', 'Concierge', 'Cuisine équipée', 'Internet', 'Cheminée',
       'Sécurité', 'Chambre rangement', 'Parquet', 'Ascenseur',
       'Chauffage central', 'Salon Marocain', 'Machine à laver', 'Garage',
       'Marbre', 'Porte blindée', 'Vue sur les montagnes', 'Climatisation',
       'Jardin', 'Antenne parabolique', 'Double vitrage', 'Terrasse',
       'Carrelage', 'Micro-ondes', 'Four', 'prix/m²'],
      dtype='object')

In [19]:
count_null= {}
for col in df.columns:
    count_null[col] = df[col].isnull().sum()
    
count_null

{'date': 0,
 'arrondissement': 0,
 'offer link': 0,
 'title': 0,
 'price': 1160,
 'localization': 0,
 'description': 688,
 'more': 0,
 'caracteristiques': 0,
 'X': 0,
 'Y': 0,
 'type_link': 0,
 'type_title': 0,
 'surface': 144,
 'pieces': 338,
 'chambre': 162,
 'bains': 246,
 'age': 2742,
 'etage': 3418,
 'Réfrigérateur': 7146,
 'Salon européen': 5266,
 'TV': 7240,
 'Vue sur mer': 7994,
 'Piscine': 7583,
 'Concierge': 4666,
 'Cuisine équipée': 3960,
 'Internet': 7178,
 'Cheminée': 6509,
 'Sécurité': 5137,
 'Chambre rangement': 6656,
 'Parquet': 7974,
 'Ascenseur': 4130,
 'Chauffage central': 7374,
 'Salon Marocain': 4808,
 'Machine à laver': 7281,
 'Garage': 3214,
 'Marbre': 5516,
 'Porte blindée': 7028,
 'Vue sur les montagnes': 8269,
 'Climatisation': 5603,
 'Jardin': 5996,
 'Antenne parabolique': 5345,
 'Double vitrage': 6891,
 'Terrasse': 4154,
 'Carrelage': 6867,
 'Micro-ondes': 7477,
 'Four': 5959,
 'prix/m²': 1296}